--[[ shared ]]
L["All"] = "" -- memory.lua, guildlog.lua
L["Alt"] = "" -- shared.lua
L["Alt+Click"] = "" -- shared.lua, friends.lua, guild.lua
L["Alt+Left-click"] = "" -- shared.lua
L["Alt+Right-click"] = "" -- shared.lua
L["Are you sure you want to Reload the UI?"] = "" -- gamemenu.lua, stuff.lua
L["Bags"] = "" -- bags.lua, durability.lua
L["Broker button options"] = "" -- shared.lua
L["Character"] = "" -- friends.lua, durability.lua, guild.lua, guildlog.lua
L["Choose your fav. combination of modifier and mouse key to "] = "" -- shared.lua
L["Click"] = "" -- shared.lua, fps.lua, friends.lua, xp.lua, equipment.lua, questlog.lua, nameplates.lua, gold.lua, volume.lua, garrison.lua, guild.lua, tracking.lua
L["Ctrl"] = "" -- shared.lua
L["Ctrl+Click"] = "" -- shared.lua, fps.lua, equipment.lua
L["Ctrl+Left-click"] = "" -- shared.lua
L["Ctrl+Right-click"] = "" -- shared.lua
L["Disabled"] = "" -- shared.lua, optionspanel.lua, followers.lua
L["Do you really want to left the game?"] = "" -- gamemenu.lua, stuff.lua
L["Do you really want to logout from this character?"] = "" -- gamemenu.lua, stuff.lua
L["Do you really want to reload the UI?"] = "" -- gamemenu.lua, stuff.lua
L["Do you really want to switch display mode?"] = "" -- gamemenu.lua, stuff.lua
L["Follower"] = "" -- followers.lua, missions.lua
L["Friendly"] = "" -- durability.lua, gps.lua
L["Hold '..mod])..' || '..C('green',L['Show expire date instead of duration"] = "" -- ids.lua, professions.lua, garrison.lua
L["Hold shift"] = "" -- questlog.lua, missions.lua
L["Left alt"] = "" -- shared.lua
L["Left ctrl"] = "" -- shared.lua
L["Left shift"] = "" -- shared.lua
L["Left-click"] = "" -- shared.lua, optionspanel.lua, friends.lua, dualspec.lua, gamemenu.lua, gps.lua, stuff.lua, memory.lua
L["Level"] = "" -- friends.lua, questlog.lua, followers.lua, missions.lua, clock.lua, guild.lua
L["Logout"] = "" -- gamemenu.lua, stuff.lua
L["Max."] = "" -- fps.lua, garrison.lua
L["Name"] = "" -- framenames.lua, garrison.lua
L["No data found"] = "" -- durability.lua, xp.lua
L["No sets found"] = "" -- chatcommand.lua, equipment.lua
L["None"] = "" -- core.lua, optionspanel.lua, nameplates.lua
L["Notes"] = "" -- friends.lua, guild.lua
L["Open character info"] = "" -- durability.lua, equipment.lua
L["Open guild roster"] = "" -- guild.lua, guildlog.lua
L["Open option menu"] = "" -- bags.lua, durability.lua, latency.lua, archaeology.lua, equipment.lua, mail.lua, calendar.lua, clock.lua, guild.lua
L["Options"] = "" -- shared.lua, optionspanel.lua, latency.lua
L["Place"] = "" -- currency.lua, professions.lua
L["Precision"] = "" -- speed.lua, gps.lua
L["Quit game"] = "" -- gamemenu.lua, stuff.lua
L["Reload UI"] = "" -- gamemenu.lua, stuff.lua
L["Right alt"] = "" -- shared.lua
L["Right ctrl"] = "" -- shared.lua
L["Right shift"] = "" -- shared.lua
L["Right-click"] = "" -- shared.lua, optionspanel.lua, dualspec.lua, latency.lua, gamemenu.lua, mail.lua, gold.lua, gps.lua, stuff.lua, memory.lua
L["Shift"] = "" -- shared.lua
L["Shift+Click"] = "" -- shared.lua, fps.lua, equipment.lua
L["Shift+Left-click"] = "" -- shared.lua, gamemenu.lua, stuff.lua
L["Shift+Right-click"] = "" -- shared.lua, memory.lua
L["Suffix coloring"] = "" -- core.lua, latency.lua
L["Then push again..."] = "" -- gamemenu.lua, stuff.lua
L["This option is disabled"] = "" -- mail.lua, calendar.lua, tracking.lua
L["Type"] = "" -- ids.lua, missions.lua
L["Unknown"] = "" -- bags.lua, framenames.lua, followers.lua
L["XP"] = "" -- xp.lua, followers.lua, guild.lua
L["Zone"] = "" -- friends.lua, gps.lua, guild.lua
L["iLevel"] = "" -- equipment.lua, followers.lua, missions.lua
L["open the character info"] = "" -- durability.lua, equipment.lua
L["open the guild roster"] = "" -- guild.lua, guildlog.lua
L["open the option menu"] = "" -- bags.lua, durability.lua, archaeology.lua, equipment.lua, calendar.lua, clock.lua

--[[ archaeology ]]
L["Archaeology"] = ""
L["Artifacts"] = ""
L["Azeroth"] = ""
L["Broker to show your archaeology artifacts."] = ""
L["Draenor"] = ""
L["Fragments"] = ""
L["Keystones"] = ""
L["Northend"] = ""
L["Open archaeology frame"] = ""
L["Order archaeology races by continent"] = ""
L["Order by continent"] = ""
L["Outland"] = ""
L["Pandaria"] = ""
L["Races"] = ""
L["open your archaeology frame"] = ""

--[[ bags ]]
L["All qualities"] = ""
L["All qualities (+ vendor price)"] = ""
L["Broker to show filled, total and free count of blag slots"] = ""
L["Choose your favorite"] = ""
L["Count"] = ""
L["Crap selling options"] = ""
L["Critical low free slots"] = ""
L["Display a list of item qualities"] = ""
L["Enable crap selling"] = ""
L["Enable crap/junk selling on opening a mergant frame."] = ""
L["Free slots"] = ""
L["Non empty qualities"] = ""
L["Non empty qualities (+ vendor price)"] = ""
L["Open bags"] = ""
L["Quality"] = ""
L["Quality list"] = ""
L["Select the maximum free slot count to coloring in red."] = ""
L["Select the maximum free slot count to coloring in yellow."] = ""
L["Show bagspace instead used and max. bagslots in broker button"] = ""
L["Show freespace"] = ""
L["Show quality"] = ""
L["Total slots"] = ""
L["Vendor price"] = ""
L["Warn low free slots"] = ""
L["free"] = ""
L["open your bags"] = ""
L["poor and common"] = ""
L["poor and common (+ vendor price)"] = ""
L["poor only"] = ""
L["poor only (+ vendor price)"] = ""

--[[ calendar ]]
L["%s found. It's unsave to hide the minimap mail icon without errors."] = ""
L["%s has a similar option to hide the minimap mail icon."] = ""
L["%s has its own mail icon."] = ""
L["(current)"] = ""
L["(soon)"] = ""
L["Broker to show invitations"] = ""
L["Calendar"] = ""
L["Events"] = ""
L["Hide Blizzard's minimap calendar button"] = ""
L["Hide calendar button"] = ""
L["Invitation"] = ""
L["Invitations"] = ""
L["No invitations found"] = ""
L["Open calendar"] = ""
L["Reduce the broker text to a number without text"] = ""
L["Shorter Broker"] = ""
L["open the calendar"] = ""
L["to"] = ""

--[[ chatchannels ]]
L["ChatChannels"] = ""
L["Display chat channels with count of users."] = ""
L["No channels listed..."] = ""
L["collapsed"] = ""

--[[ chatcommand ]]
L["Available Sets:"] = ""
L["Broker_Everything will use the new setting on next reload."] = ""
L["Cfg"] = ""
L["Change number of displayed addons in module memory."] = ""
L["Chat command list for /be & /broker_everything"] = ""
L["Data modules:"] = ""
L["Disabling %s on next reload."] = ""
L["Enable/disable tooltip scaling."] = ""
L["Enabling %s on next reload."] = ""
L["Equip a set."] = ""
L["Equipment"] = ""
L["Hide/Show tooltip hint."] = ""
L["Info"] = ""
L["List of available modules with his status"] = ""
L["Name of Equipmentset are invalid"] = ""
L["Open options panel"] = ""
L["Reset all module settings"] = ""
L["Showing a maximum of %d addons."] = ""
L["Showing all addons."] = ""
L["Switch between global and per character saved settings"] = ""
L["Usage: /be equip <SetName>"] = ""

--[[ clock ]]
L["Broker to show realm or local time"] = ""
L["Display the time with seconds in broker button and tooltip"] = ""
L["Local Time"] = ""
L["Local or server time"] = ""
L["Open time manager"] = ""
L["Playtime"] = ""
L["Server Time"] = ""
L["Session"] = ""
L["Show seconds"] = ""
L["Switch between local and server time in broker button"] = ""
L["Switch between time format 24 hours and 12 hours with AM/PM"] = ""
L["Total"] = ""
L["UTC Time"] = ""
L["open the time manager"] = ""

--[[ core ]]
L["Adjust the maximum of tooltip height in percent of your screen height."] = ""
L["Allow mouseover"] = ""
L["Broker as Minimap Buttons"] = ""
L["Change the color of the icons"] = ""
L["Choose an custom iconset"] = ""
L["DataBroker options"] = ""
L["Default (no modifier)"] = ""
L["Enable/Disable class coloring of the information display suffixes. (eg, ms, fps etc)"] = ""
L["Enable/Disable use of global Broker_Everything profile across all of your characters."] = ""
L["Gold coloring"] = ""
L["Hide copper"] = ""
L["Hide copper and silver values of your money"] = ""
L["Hide copper values of your money"] = ""
L["Hide lower zero values of your money"] = ""
L["Hide lower zeros"] = ""
L["Hide silver"] = ""
L["Hold modifier key to display tooltip"] = ""
L["Hold modifier key to use mouseover in tooltip"] = ""
L["Icon color"] = ""
L["Icon options"] = ""
L["Iconsets"] = ""
L["Max. Tooltip height"] = ""
L["Misc options"] = ""
L["Money display options"] = ""
L["Scale the tooltips with your UIScale."] = ""
L["Screen capture mode"] = ""
L["Show hints"] = ""
L["Show hints in tooltips."] = ""
L["Show tooltip"] = ""
L["The screen capture mode replaces all characters of a name with wildcards (*) without the first. Your chars in XP, your friends battleTags/RealID and there character names and the character names in your guild and there notes."] = ""
L["Tooltip Scaling"] = ""
L["Tooltip options"] = ""
L["Use LibDBIcon to add Broker to Minimap"] = ""
L["Use colors instead of icons for gold, silver and copper"] = ""
L["Use global profile"] = ""
L["Use prefix"] = ""
L["Use prefix 'BE..' on module registration at LibDataBroker. This fix problems with other addons with same broker names but effect your current settings in panel addons like Bazooka or Titan Panel."] = ""
L["Warning"] = ""
L["saved variables have been reset."] = ""

--[[ currency ]]
L["Add a currency"] = ""
L["Auto"] = ""
L["Broker to show your different currencies."] = ""
L["Currency in title - menu"] = ""
L["Display as favorite selected currencies only."] = ""
L["Favorite mode"] = ""
L["Left"] = ""
L["Over"] = ""
L["Remove the currency"] = ""
L["Right"] = ""
L["Second tooltip"] = ""
L["Under"] = ""
L["Where does the second tooltip for a single currency are displayed from the first tooltip"] = ""
L["display the content of the tooltip shorter"] = ""
L["short Tooltip"] = ""

--[[ dualspec ]]
L["%d unspent talent"] = ""
L["%d unspent talents"] = ""
L["Active"] = ""
L["Broker to show and switch your character specializations"] = ""
L["Dualspec"] = ""
L["No Spec!"] = ""
L["No specialisation found"] = ""
L["Open talents pane"] = ""
L["Switch spec."] = ""
L["Talents"] = ""
L["Unspent talents: %d"] = ""

--[[ durability ]]
L["(session only)"] = ""
L["AutoRepair"] = ""
L["Automatic repair failed. Not enough money..."] = ""
L["Automaticly repair your equipment on opening a merchant with repair option."] = ""
L["Automaticly repaired with guild money"] = ""
L["Automaticly repaired with player money"] = ""
L["Average"] = ""
L["Broker format"] = ""
L["Broker to show durability of your gear and estimated repair costs."] = ""
L["Choose how much entries the list of repair costs can have."] = ""
L["Choose the date format if used in the list of repair costs"] = ""
L["Choose your favorite color set in which the percent text in broker should be displayed."] = ""
L["Choose your favorite display format for the broker button."] = ""
L["Date format"] = ""
L["Display a list of the last repair costs in tooltip"] = ""
L["Display the lowest item durability in broker."] = ""
L["Enable auto repair"] = ""
L["Exalted"] = ""
L["Honoured"] = ""
L["Last %d repair costs"] = ""
L["List of repair costs"] = ""
L["Lowest durability"] = ""
L["Lowest item"] = ""
L["Max. list entries"] = ""
L["Neutral"] = ""
L["Percent color set"] = ""
L["Post repair actions in chatframe"] = ""
L["Repair info"] = ""
L["Repair options"] = ""
L["RepairAll"] = ""
L["Reputation discounts"] = ""
L["Reset last repairs"] = ""
L["Revered"] = ""
L["Save repair costs"] = ""
L["Save the list of repair costs over the session"] = ""
L["Show discount"] = ""
L["Show list of reputation discounts in tooltip"] = ""
L["SingleRepairSummary"] = ""
L["Try fallback to player money."] = ""
L["Use guild money"] = ""
L["Use guild money on auto repair if you can"] = ""
L["Your guild leadership denied the use of guild money for auto repair."] = ""
L["by guild fund"] = ""
L["by player money"] = ""

--[[ equipment ]]
L["All slots are empty"] = ""
L["Broker to show, equip, delete, update and save equipment sets"] = ""
L["Display a list of currently equipped items."] = ""
L["Display a list of your equipment sets."] = ""
L["Display your average item level on broker button"] = ""
L["Enable it from the character info"] = ""
L["Equipment manager is not enabled"] = ""
L["Item is not enchanted."] = ""
L["No equipment sets found"] = ""
L["Not enchanted!"] = ""
L["Sets"] = ""
L["Show Equipment sets"] = ""
L["Show average item level"] = ""
L["Show inventory"] = ""
L["Unknown Set"] = ""
L["to delete"] = ""
L["to equip"] = ""
L["to update/save"] = ""

--[[ followers ]]
L["Abilities"] = ""
L["Available"] = ""
L["Background colored row for status"] = ""
L["Broker to show a list of your follower with level, quality, xp and more."] = ""
L["Hide disabled followers"] = ""
L["Hide disabled followers in tooltip"] = ""
L["Hide working followers"] = ""
L["Hide working followers in tooltip"] = ""
L["No followers found..."] = ""
L["Traits"] = ""
L["Use background colored row for follower status instead to split in separate tables"] = ""

--[[ fps ]]
L["Broker to show your frames per second."] = ""
L["Current"] = ""
L["Delete a set"] = ""
L["Experimental"] = ""
L["FPS"] = ""
L["Min."] = ""
L["No set found"] = ""
L["Open graphics menu"] = ""
L["Open graphics set manager"] = ""
L["Right-Click"] = ""
L["Update/save a set"] = ""
L["Use a set"] = ""

--[[ framenames ]]
L["Broker to show names of frames under the mouse."] = ""
L["Framenames"] = ""

--[[ friends ]]
L["BattleNet"] = ""
L["BattleTag"] = ""
L["Broker to show you which friends are online."] = ""
L["Characters"] = ""
L["Disable displaying game icons and use game shortcut instead of"] = ""
L["Disable game icons"] = ""
L["Faction"] = ""
L["Friends"] = ""
L["Game"] = ""
L["Invite a friend"] = ""
L["My current broadcast message"] = ""
L["No friends online."] = ""
L["Open friends roster"] = ""
L["Real ID"] = ""
L["Realm"] = ""
L["Show BattleTags in tooltip"] = ""
L["Show BattleTags in tooltip behind the realID"] = ""
L["Split Characters and BattleNet-Friends in Tooltip"] = ""
L["Split Characters and BattleNet-Friends on Broker Button"] = ""
L["Split friends|nin Tooltip"] = ""
L["Split friends|non Broker"] = ""
L["Whisper with a friend"] = ""

--[[ gamemenu ]]
L["A broker that merge blizzards game menu, microbutton bar and more into one tooltip with clickable elements. It is not recommented to use it in combat."] = ""
L["Cancel ticket"] = ""
L["Custom title"] = ""
L["Custom title in tooltip"] = ""
L["Disable Click options"] = ""
L["Disable the click options on broker button"] = ""
L["Edit ticket"] = ""
L["Game Menu"] = ""
L["Hide section 2"] = ""
L["Hide section 2 in tooltip"] = ""
L["Hide section 3"] = ""
L["Hide section 3 in tooltip"] = ""
L["Open GM Ticket"] = ""
L["Set your own Title instead of 'Game Menu'"] = ""
L["Show GMTicket"] = ""
L["Show GMTickets in tooltip and average wait time in broker button"] = ""
L["Show all entries there taint the environment. Be carefull. Can produce error in combat."] = ""
L["Show tainting entries"] = ""
L["Use custom title as tooltip title"] = ""

--[[ garrison ]]
L["Available blueprints level 3"] = ""
L["Broker to buildings of your garrison and there active work orders."] = ""
L["Garrison"] = ""
L["Garrison cache forcast"] = ""
L["In|nprogress"] = ""
L["More info in tooltip..."] = ""
L["Necessary achievements for blueprints level 3"] = ""
L["No data found..."] = ""
L["No data to display..."] = ""
L["Open achievement"] = ""
L["Ready"] = ""
L["Under construction"] = ""
L["Upgrade finished"] = ""
L["free job"] = ""

--[[ gold ]]
L["Broker to show gold information. Shows gold amounts for characters on the same ns.realm and faction and the amount made or lost for the session."] = ""
L["Gold"] = ""
L["Gold information"] = ""
L["Open currency pane"] = ""
L["Remove entry"] = ""
L["Session loss"] = ""
L["Session profit"] = ""
L["Total Gold"] = ""

--[[ gps ]]
L["Arena"] = ""
L["Broker to show the name of the current Zone and the co-ordinates."] = ""
L["Broker to show the name of the current zone."] = ""
L["Broker to show your current co-ordinates within the zone."] = ""
L["Change how much digits display after the dot."] = ""
L["Co-ordinates"] = ""
L["Co-ordinates indeterminable"] = ""
L["Co-ordination format"] = ""
L["Combat"] = ""
L["Contested"] = ""
L["Display in broker zone and subzone if exists or one of it."] = ""
L["Display the transport menu without names of spells and items behind the icons."] = ""
L["Display zone names"] = ""
L["GPS"] = ""
L["GPS / Location / ZoneText"] = ""
L["Hostile"] = ""
L["How would you like to view co-ordinations."] = ""
L["Inn"] = ""
L["Items"] = ""
L["Location"] = ""
L["No spells or items found"] = ""
L["Open World map"] = ""
L["Open transport menu"] = ""
L["Sanctuary"] = ""
L["Short transport menu"] = ""
L["Some shared options for the modules GPS, Location and ZoneText"] = ""
L["Sorry"] = ""
L["Subzone"] = ""
L["Zone status"] = ""
L["ZoneText"] = ""

--[[ guild ]]
L["<<empty>>"] = ""
L["Applicant"] = ""
L["Broker to show guild information. Guild members currently online, MOTD, guild xp etc."] = ""
L["Comment"] = ""
L["Damage"] = ""
L["Display mobile chatter with own table in tooltip"] = ""
L["Enable/Disable the display of Guild Reputation in the Guild data broker tooltip."] = ""
L["Expired"] = ""
L["Guild"] = ""
L["Healer"] = ""
L["Invite a member"] = ""
L["MobileChat"] = ""
L["MotD:"] = ""
L["No Guild"] = ""
L["No Text"] = ""
L["Officer notes"] = ""
L["Professions"] = ""
L["Rank"] = ""
L["Rep"] = ""
L["Roles"] = ""
L["Secondary tooltip options"] = ""
L["Separate mobile chatter"] = ""
L["Show Guild Message of the Day in tooltip"] = ""
L["Show Guild MotD"] = ""
L["Show applicants"] = ""
L["Show applicants in broker and tooltip"] = ""
L["Show count of mobile chatter in broker button"] = ""
L["Show current zone from guild member"] = ""
L["Show current zone from guild members"] = ""
L["Show guild reputation"] = ""
L["Show mobile chatter"] = ""
L["Show mobile chatter in broker"] = ""
L["Show mobile chatter in tooltip (Armory App users)"] = ""
L["Show notes"] = ""
L["Show notes from guild member"] = ""
L["Show notes from guild members"] = ""
L["Show officer notes"] = ""
L["Show officer notes from guild member"] = ""
L["Show officer notes from guild members. (This option will be ignored if you have not permission to read the officer notes)"] = ""
L["Show professions"] = ""
L["Show professions from guild member"] = ""
L["Show professions from guild members"] = ""
L["Show rank"] = ""
L["Show rank name from guild members"] = ""
L["Show realm name"] = ""
L["Show realm names behind guild and character names. Guilds and characters from connected-realms gets an asterisk behind the names if this option is unchecked."] = ""
L["Show zone"] = ""
L["Tank"] = ""
L["The secondary tooltip will be displayed by moving the mouse over a guild member in main tooltip. The tooltip will be displayed if one of the following options activated."] = ""
L["Whisper with a member"] = ""
L["unlearned"] = ""

--[[ guildlog ]]
L["Action"] = ""
L["By"] = ""
L["Change the list style."] = ""
L["Demoted"] = ""
L["Display mode"] = ""
L["GuildLog"] = ""
L["Hide all entries with 'Demote' as action."] = ""
L["Hide all entries with 'Invite' as action."] = ""
L["Hide all entries with 'Join' as action."] = ""
L["Hide all entries with 'Leave' as action."] = ""
L["Hide all entries with 'Promote' as action."] = ""
L["Hide all entries with 'Remove' as action."] = ""
L["Hide demotions"] = ""
L["Hide invites"] = ""
L["Hide joins"] = ""
L["Hide leaves"] = ""
L["Hide promotions"] = ""
L["Hide removes"] = ""
L["Invited"] = ""
L["Joined"] = ""
L["Leaved"] = ""
L["New rank"] = ""
L["No log entries found..."] = ""
L["Normal list of log entries"] = ""
L["Promoted"] = ""
L["Recently"] = ""
L["Removed"] = ""
L["Select the maximum number of entries from the guild log, otherwise drag to 'All'."] = ""
L["Separate tables by actions and 'Show max. entries' used per table."] = ""
L["Show max. entries"] = ""
L["Show realm names"] = ""
L["Show realm names after character names from other realms (connected realms)."] = ""
L["a broker to show the last entries of the guild log"] = ""
L["latest %d entries"] = ""

--[[ ids ]]
L["Bosses"] = ""
L["Broker to show raid, dungeon and other lockout id's. (+World bosses)"] = ""
L["World bosses"] = ""

--[[ latency ]]
L["Broker to show your current latency. Can be configured to show both Home and/or World latency."] = ""
L["Enable/Disable the display of the latency to the home realm"] = ""
L["Enable/Disable the display of the latency to the world realms"] = ""
L["Home"] = ""
L["Latency"] = ""
L["Show home"] = ""
L["Show world"] = ""
L["World"] = ""

--[[ mail ]]
L["Broker to alert you if you have mail."] = ""
L["Display a list of chars on all realms with there mail counts and 3 lowest days before return to sender. Chars with empty mail box aren't displayed."] = ""
L["Enable to play a sound on receiving a new mail message. Default is off"] = ""
L["Hide minimap mail icon"] = ""
L["Last 3 new mails"] = ""
L["Leave in mailbox"] = ""
L["List mails on chars"] = ""
L["Mail"] = ""
L["Mail from"] = ""
L["New mail"] = ""
L["No Mail"] = ""
L["No data"] = ""
L["Play sound on new mail"] = ""
L["Stored mails"] = ""
L["mails"] = ""
L["of"] = ""

--[[ memory ]]
L["Addon"] = ""
L["Addon panel"] = ""
L["Broker to show how much memory are consumed through your addons."] = ""
L["Choose your addon panel that opens if you rightclick on memory broker or disable the right click option."] = ""
L["Collect garbage"] = ""
L["Collecting Garbage..."] = ""
L["Memory"] = ""
L["Memory Usage"] = ""
L["None (disable right click)"] = ""
L["Open interface options"] = ""
L["Select the maximum number of addons to display, otherwise drag to 'All'."] = ""
L["Show addons in tooltip"] = ""
L["The 'Script ran too long' error has multible factors. This module can produce this error if you have to much addons and you are in combat. Uncheck it to stop updating in combat."] = ""
L["Total Memory usage"] = ""
L["Update disabled while you are in combat"] = ""
L["Update while in combat"] = ""

--[[ missions ]]
L["Broker to show active and available missions for your followers."] = ""
L["Missions"] = ""
L["No missions found..."] = ""
L["Show followers on missions"] = ""

--[[ nameplates ]]
L["Broker to allow you to toggle the various nameplates. Eg, friendly or hostile."] = ""
L["Hidden"] = ""
L["Misc"] = ""
L["Nameplates"] = ""
L["Names"] = ""
L["Names/Nameplates on/off"] = ""
L["Shown"] = ""

--[[ optionspanel ]]
L["Allows you to adjust the display options."] = ""
L["An UI reload is necessary to apply all changes."] = ""
L["Default: %s"] = ""
L["Disable all modules"] = ""
L["Disable this module"] = ""
L["Display the options for this module"] = ""
L["Enable all modules"] = ""
L["Enable this module"] = ""
L["Enable/Disable the module"] = ""
L["Enabled"] = ""
L["General options"] = ""
L["Module options"] = ""
L["Modules"] = ""
L["Opens a little menu with 3 reset options"] = ""
L["Reloads your user interface. (It does not save changes)"] = ""
L["Reset all data"] = ""
L["Reset config"] = ""
L["Reset unsaved changes"] = ""
L["Resets your global and module settings but not collected data about your twinks to display mail, profession cooldowns and more."] = ""
L["Resets your last unsaved changes. Not more..."] = ""
L["Save changes without closing the option panel"] = ""
L["Show options"] = ""
L["This module has no options"] = ""
L["With options"] = ""
L["Without options"] = ""
L["Your current settings and all other data collected by some modules like mail on other chars or profession cooldowns of your twinks."] = ""

--[[ professions ]]
L["Add a profession"] = ""
L["Cooldowns"] = ""
L["Display a list of your professions"] = ""
L["In title"] = ""
L["Jewels cooldown group"] = ""
L["Leather cooldown group"] = ""
L["Open"] = ""
L["Remove"] = ""
L["Show cooldowns"] = ""
L["Show dig site status"] = ""
L["Show dig site status in broker button."] = ""
L["Show/Hide profession cooldowns from all characters."] = ""
L["Transmutation cooldown group"] = ""

--[[ questlog ]]
L["Active quests"] = ""
L["Broker to show count of quests in your questlog and quest titles in tooltip."] = ""
L["Choose your favorite website for further informations to a quest."] = ""
L["Completed quests"] = ""
L["Failed quests"] = ""
L["Fav. website"] = ""
L["Open QuestLog and select quest"] = ""
L["Quest Log"] = ""
L["QuestId"] = ""
L["Show group member name with same quests"] = ""
L["Show quest id's"] = ""
L["Show quest id's in tooltip."] = ""
L["share"] = ""

--[[ speed ]]
L["Adjust the count of numbers behind the dot."] = ""
L["Flight licences"] = ""
L["How fast are you swimming, walking, riding or flying."] = ""
L["Riding skill"] = ""
L["Speed"] = ""
L["Speed bonus"] = ""

--[[ stuff ]]
L["Broker to allow you to do...Stuff! Switch to windowed mode, reload ui, logout and quit."] = ""
L["Quit Game"] = ""
L["Stuff"] = ""
L["Switch window/fullscreen mode"] = ""
L["Windowed / Fullscreen"] = ""

--[[ surprise ]]
L["(Unknown)"] = ""
L["(finished)"] = ""
L["Broker to have an eye on your suprise item. What is a suprise item? Anything thats needs some days to open it and thats lootable after the time. Can contain random objects like mounts, companions and more."] = ""
L["No item found."] = ""
L["Surprise"] = ""

--[[ tracking ]]
L["%s found. It's unsave to hide the minimap tracking icon without errors."] = ""
L["%s has a similar option to hide the minimap tracking icon."] = ""
L["%s has its own tracking icon."] = ""
L["Broker to show what you are currently tracking. You can also change the tracking types from this broker."] = ""
L["Display one of the selected tracking options in broker text."] = ""
L["Display selection"] = ""
L["Hide blizzard's tracking button on minimap"] = ""
L["Hide minimap button"] = ""
L["No tracking option active."] = ""
L["Open tracking menu"] = ""
L["Tracking"] = ""

--[[ volume ]]
L["Change Volumes and toggle some audio options."] = ""
L["Change steps"] = ""
L["Change the stepping width for volume changes with mousewheel and clicks."] = ""
L["Display in tooltip a list of your sound output hardware."] = ""
L["List of hardware"] = ""
L["Louder"] = ""
L["Mousewheel"] = ""
L["On/Off"] = ""
L["Quieter"] = ""
L["Sorry, In combat lockdown."] = ""
L["Use MouseWheel"] = ""
L["Use the MouseWheel to change the volume"] = ""
L["Video Volume"] = ""
L["Volume"] = ""

--[[ wowtoken ]]
L["Current price:"] = ""
L["Currently no price available..."] = ""
L["Diff to previous:"] = ""
L["Last changed:"] = ""
L["Show on broker button and in tooltip the current amount of gold for a WoW Token. (Updating in two minute interval)."] = ""
L["WoWToken"] = ""

--[[ xp ]]
L["Back"] = ""
L["Broker to show your xp. Can be shown either as a percentage, or as values."] = ""
L["Chest"] = ""
L["Delete a character from the list"] = ""
L["Display XP in broker"] = ""
L["Display a list of my chars on same realm with her level and xp"] = ""
L["Head"] = ""
L["Hide all characters who have reached the level cap."] = ""
L["Legs"] = ""
L["Max. Level reached"] = ""
L["Out of Level"] = ""
L["Recruite a Friend"] = ""
L["Rest"] = ""
L["Ring1"] = ""
L["Ring2"] = ""
L["Select to show XP as an absolute value; Deselected will show it as a percentage."] = ""
L["Shoulder"] = ""
L["Show non max. level characters only"] = ""
L["Show other chars xp"] = ""
L["Til Next Level"] = ""
L["XP bonus"] = ""
L["XP gain disabled"] = ""
L["Your other chars (%s)"] = ""
L["not equipped"] = ""
