
local addon, ns = ...
local p = "Interface\Addons\"..addon.."\media\"
local coords = {0,1,0,1} 
local coordsStr = "16:16:0:0"

LibStub("LibSharedMedia-3.0"):Register("Broker_Everything_Iconsets","<Your Iconset name>",{
	-- ["FPS_yellow"] = {iconfile=p.."", coords = coords},
	-- ["FPS_red"] = {iconfile=p.."", coords = coords},
	-- ["FPS_blue"] = {iconfile=p.."", coords = coords},
	-- ["FPS_green"] = {iconfile=p.."", coords = coords},
	-- ["Bags"] = {iconfile=p.."", coords = coords},
	-- ["WoWToken"] = {iconfile=p.."", coords = coords},
	-- ["Surprise"] = {iconfile=p.."", coords = coords},
	-- ["Friends"] = {iconfile=p.."", coords = coords},
	-- ["Dualspec"] = {iconfile=p.."", coords = coords},
	-- ["Durability"] = {iconfile=p.."", coords = coords},
	-- ["Latency"] = {iconfile=p.."", coords = coords},
	-- ["Archaeology"] = {iconfile=p.."", coords = coords},
	-- ["XP"] = {iconfile=p.."", coords = coords},
	-- ["gm_Character-neutral"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Spellbook"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Talents"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Achievments"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Questlog"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_FLGuild"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Guild"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Friends"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_PvP-neutral"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_PvP-alliance"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_PvP-horde"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Raidfinder"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_LFDungeon"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Mounts"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Pets"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_ToyBox"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_EJ"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Store"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Help"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_SysOpts"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_KeyBinds"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_UiOpts"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Macros"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_MacOpts"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Addons"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Fullscreen"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_ReloadUi"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_Logout"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_ExitGame"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_gmticket"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_gmticket_edit"] = {iconfile=p.."", coords = coordsStr},
	-- ["gm_gmticket_cancel"] = {iconfile=p.."", coords = coordsStr},
	-- ["Equipment"] = {iconfile=p.."", coords = coords},
	-- ["Nameplates"] = {iconfile=p.."", coords = coords},
	-- ["IDs"] = {iconfile=p.."", coords = coords},
	-- ["Speed"] = {iconfile=p.."", coords = coords},
	-- ["Mail"] = {iconfile=p.."", coords = coords},
	-- ["Mail_new"] = {iconfile=p.."", coords = coords},
	-- ["Mail_stored"] = {iconfile=p.."", coords = coords},
	-- ["Follower"] = {iconfile=p.."", coords = coords},
	-- ["Currency_Neutral"] = {iconfile=p.."", coords = coords},
	-- ["Currency_Horde"] = {iconfile=p.."", coords = coords},
	-- ["Currency_Alliance"] = {iconfile=p.."", coords = coords},
	-- ["Calendar"] = {iconfile=p.."", coords = coords},
	-- ["Calendar_pending"] = {iconfile=p.."", coords = coords},
	-- ["Gold"] = {iconfile=p.."", coords = coords},
	-- ["Missions"] = {iconfile=p.."", coords = coords},
	-- ["Volume_0"] = {iconfile=p.."", coords = coords},
	-- ["Volume_33"] = {iconfile=p.."", coords = coords},
	-- ["Volume_66"] = {iconfile=p.."", coords = coords},
	-- ["Volume_100"] = {iconfile=p.."", coords = coords},
	-- ["Professions"] = {iconfile=p.."", coords = coords},
	-- ["GPS"] = {iconfile=p.."", coords = coords},
	-- ["Location"] = {iconfile=p.."", coords = coords},
	-- ["ZoneText"] = {iconfile=p.."", coords = coords},
	-- ["Clock"] = {iconfile=p.."", coords = coords},
	-- ["Stuff"] = {iconfile=p.."", coords = coords},
	-- ["Garrison"] = {iconfile=p.."", coords = coords},
	-- ["Guild"] = {iconfile=p.."", coords = coords},
	-- ["Memory"] = {iconfile=p.."", coords = coords},
	-- ["Tracking"] = {iconfile=p.."", coords = coords},
})

